export const FETCH_HEALTH_DAILY_LOGS = "FETCH_HEALTH_DAILY_LOGS" as const;
export const LOAD_HEALTH_DAILY_LOGS = "LOAD_HEALTH_DAILY_LOGS" as const;
export const FETCH_EDIT_HEALTH_DAILY_WEIGHT =
  "FETCH_EDIT_HEALTH_DAILY_WEIGHT" as const;
export const LOAD_EDIT_HEALTH_DAILY_WEIGHT =
  "LOAD_EDIT_HEALTH_DAILY_WEIGHT" as const;
export const FETCH_EDIT_HEALTH_DAILY_STEPS =
  "FETCH_EDIT_HEALTH_DAILY_STEPS" as const;
export const LOAD_EDIT_HEALTH_DAILY_STEPS =
  "LOAD_EDIT_HEALTH_DAILY_STEPS" as const;
export const FETCH_HEALTH_SUPPLEMENTS = "FETCH_HEALTH_SUPPLEMENTS" as const;
export const LOAD_HEALTH_SUPPLEMENTS = "LOAD_HEALTH_SUPPLEMENTS" as const;
export const FETCH_HEALTH_SUPPLEMENT_LOGS =
  "FETCH_HEALTH_SUPPLEMENT_LOGS" as const;
export const LOAD_HEALTH_SUPPLEMENT_LOGS =
  "LOAD_HEALTH_SUPPLEMENT_LOGS" as const;
export const FETCH_TOGGLE_HEALTH_SUPPLEMENT_LOG =
  "FETCH_TOGGLE_HEALTH_SUPPLEMENT_LOG" as const;
export const LOAD_TOGGLE_HEALTH_SUPPLEMENT_LOG =
  "LOAD_TOGGLE_HEALTH_SUPPLEMENT_LOG" as const;
export const FETCH_EDIT_HEALTH_DAILY_BODYFAT =
  "FETCH_EDIT_HEALTH_DAILY_BODYFAT" as const;
export const LOAD_EDIT_HEALTH_DAILY_BODYFAT =
  "LOAD_EDIT_HEALTH_DAILY_BODYFAT" as const;
