export const FETCH_HEALTH_DAILY_LOGS = "FETCH_HEALTH_DAILY_LOGS" as const;
export const LOAD_HEALTH_DAILY_LOGS = "LOAD_HEALTH_DAILY_LOGS" as const;
export const FETCH_EDIT_HEALTH_DAILY_WEIGHT =
  "FETCH_EDIT_HEALTH_DAILY_WEIGHT" as const;
export const LOAD_EDIT_HEALTH_DAILY_WEIGHT =
  "LOAD_EDIT_HEALTH_DAILY_WEIGHT" as const;
export const FETCH_EDIT_HEALTH_DAILY_STEPS =
  "FETCH_EDIT_HEALTH_DAILY_STEPS" as const;
export const LOAD_EDIT_HEALTH_DAILY_STEPS =
  "LOAD_EDIT_HEALTH_DAILY_STEPS" as const;
export const FETCH_HEALTH_SUPPLEMENTS = "FETCH_HEALTH_SUPPLEMENTS" as const;
export const LOAD_HEALTH_SUPPLEMENTS = "LOAD_HEALTH_SUPPLEMENTS" as const;
export const FETCH_HEALTH_SUPPLEMENT_LOGS =
  "FETCH_HEALTH_SUPPLEMENT_LOGS" as const;
export const LOAD_HEALTH_SUPPLEMENT_LOGS =
  "LOAD_HEALTH_SUPPLEMENT_LOGS" as const;
export const FETCH_TOGGLE_HEALTH_SUPPLEMENT_LOG =
  "FETCH_TOGGLE_HEALTH_SUPPLEMENT_LOG" as const;
export const LOAD_TOGGLE_HEALTH_SUPPLEMENT_LOG =
  "LOAD_TOGGLE_HEALTH_SUPPLEMENT_LOG" as const;
export const FETCH_EDIT_HEALTH_DAILY_BODYFAT =
  "FETCH_EDIT_HEALTH_DAILY_BODYFAT" as const;
export const LOAD_EDIT_HEALTH_DAILY_BODYFAT =
  "LOAD_EDIT_HEALTH_DAILY_BODYFAT" as const;
export const FETCH_EDIT_HEALTH_DAILY_WATER =
  "FETCH_EDIT_HEALTH_DAILY_WATER" as const;
export const LOAD_EDIT_HEALTH_DAILY_WATER =
  "LOAD_EDIT_HEALTH_DAILY_WATER" as const;
export const FETCH_EDIT_HEALTH_DAILY_CALORIES =
  "FETCH_EDIT_HEALTH_DAILY_CALORIES" as const;
export const LOAD_EDIT_HEALTH_DAILY_CALORIES =
  "LOAD_EDIT_HEALTH_DAILY_CALORIES" as const;
export const FETCH_EDIT_HEALTH_DAILY_SLEEP =
  "FETCH_EDIT_HEALTH_DAILY_SLEEP" as const;
export const LOAD_EDIT_HEALTH_DAILY_SLEEP =
  "LOAD_EDIT_HEALTH_DAILY_SLEEP" as const;
export const FETCH_HEALTH_DIET_LOGS_LATEST =
  "FETCH_HEALTH_DIET_LOGS_LATEST" as const;
export const LOAD_HEALTH_DIET_LOGS_LATEST =
  "LOAD_HEALTH_DIET_LOGS_LATEST" as const;
export const FETCH_APPS = "FETCH_APPS" as const;
export const LOAD_APPS = "LOAD_APPS" as const;
export const FETCH_DIET_LOGS = "FETCH_DIET_LOGS" as const;
export const LOAD_DIET_LOGS = "LOAD_DIET_LOGS" as const;
export const FETCH_EDIT_DIET_LOG = "FETCH_EDIT_DIET_LOG" as const;
export const LOAD_EDIT_DIET_LOG = "LOAD_EDIT_DIET_LOG" as const;
export const FETCH_DELETE_DIET_LOG = "FETCH_DELETE_DIET_LOG" as const;
export const LOAD_DELETE_DIET_LOG = "LOAD_DELETE_DIET_LOG" as const;
// Checkins
export const FETCH_CHECKINS = "FETCH_CHECKINS" as const;
export const LOAD_CHECKINS = "LOAD_CHECKINS" as const;
export const FETCH_EDIT_CHECKIN = "FETCH_EDIT_CHECKIN" as const;
export const LOAD_EDIT_CHECKIN = "LOAD_EDIT_CHECKIN" as const;
export const FETCH_DELETE_CHECKIN = "FETCH_DELETE_CHECKIN" as const;
export const LOAD_DELETE_CHECKIN = "LOAD_DELETE_CHECKIN" as const;
// Check-in Attachments
export const FETCH_CHECKIN_ATTACHMENTS = "FETCH_CHECKIN_ATTACHMENTS" as const;
export const LOAD_CHECKIN_ATTACHMENTS = "LOAD_CHECKIN_ATTACHMENTS" as const;
